name: Post welcome comment
on:
  pull_request:
    branches: ["main"]

jobs:
  secret-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install necessary packages
        run: |
          pip install git+https://github.com/NASA-AMMOS/slim-detect-secrets.git@exp
          pip install jq

      - name: Create an initial .secrets.baseline if .secrets.baseline does not exist
        run: |
          if [ ! -f .secrets.baseline ]; then
            echo "⚠️ No existing .secrets.baseline file detected. Creating a new blank baseline file."
            mkdir empty-dir
            detect-secrets scan empty-dir > .secrets.baseline
            echo "✅ Blank .secrets.baseline file created successfully."
            rm -r empty-dir
          else
            echo "✅ Existing .secrets.baseline file detected. No new baseline file will be created."
          fi

      - uses: actions/checkout@v2
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Scan repository for secrets
        run: |
          cp .secrets.baseline .secrets.new
          detect-secrets scan --baseline .secrets.new --exclude-files '.secrets.*' --exclude-files '.git*'

          compare_secrets() { diff <(jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$1" | sort) <(jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$2" | sort) >/dev/null; }

          if ! compare_secrets .secrets.baseline .secrets.new; then
            echo "⚠️ Attention Required! ⚠️" >&2
            echo "New secrets have been detected..." >&2
            exit 1
          fi
